### ISSUE TITLE
Building mxc_mipi_csi2 as a module results in incorrect images from mipi

### ISSUE THREAD

**Issue by Olangu** [boundarydevices/linux#50]
Something seem to be wrong with the mxc_mipi_csi2 driver.
When build as a module instead of built in to the kernel all YUV images fetched over mipi is erroneous. The luma component goes missing.

Re-building in kernel results in no problems.

To reproduce:
Change CONFIG_MXC_MIPI_CSI2=y to CONFIG_MXC_MIPI_CSI2=m

Boot on new kernel and try video from OV5640 for example.

This might need to be reported upstream.

**Comment by gibsson** [comment]
Can't repro on latest branch.
