### ISSUE TITLE
missing integer.pm package during make

### ISSUE THREAD

**Issue by zohargolan** [boundarydevices/linux#70]
CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  PERLASM arch/arm64/crypto/sha256-core.S
Can't locate integer.pm in @INC (you may need to install the integer module) (@INC contains: /home/eotech/projects/dnvd/kernel/boundary-devices/sdk/boundary-xwayland/3.3/sysroots/x86_64-fslcsdk-linux/usr/bin/../..//usr/lib/perl5/site_perl/5.32.1/x86_64-linux /home/eotech/projects/dnvd/kernel/boundary-devices/sdk/boundary-xwayland/3.3/sysroots/x86_64-fslcsdk-linux/usr/bin/../..//usr/lib/perl5/site_perl/5.32.1 /home/eotech/projects/dnvd/kernel/boundary-devices/sdk/boundary-xwayland/3.3/sysroots/x86_64-fslcsdk-linux/usr/bin/../..//usr/lib/perl5/vendor_perl/5.32.1 /home/eotech/projects/dnvd/kernel/boundary-devices/sdk/boundary-xwayland/3.3/sysroots/x86_64-fslcsdk-linux/usr/bin/../..//usr/lib/perl5/5.32.1/x86_64-linux /home/eotech/projects/dnvd/kernel/boundary-devices/sdk/boundary-xwayland/3.3/sysroots/x86_64-fslcsdk-linux/usr/bin/../..//usr/lib/perl5/5.32.1 /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/site_perl/5.32.1/x86_64-linux /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/site_perl/5.32.1 /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/vendor_perl/5.32.1/x86_64-linux /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/vendor_perl/5.32.1 /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/5.32.1/x86_64-linux /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-fslcsdk-linux/usr/lib/perl5/5.32.1) at arch/arm64/crypto/sha512-armv8.pl line 478.
BEGIN failed--compilation aborted at arch/arm64/crypto/sha512-armv8.pl line 478.
make[2]: *** [arch/arm64/crypto/Makefile:78: arch/arm64/crypto/sha256-core.S] Error 2
make[1]: *** [scripts/Makefile.build:540: arch/arm64/crypto] Error 2
make: *** [Makefile:1868: arch/arm64] Error 2

**Comment by gibsson** [comment]
Please specify:
- which branch are you building?
- which defconfig?
- how are you building it?
- what compiler and its version?
It seems to be Yocto, are you using latest release (Honister)? Also, is it up to date (repo sync)?
FYI, our kernel is built automatically by the build server.
